ofdpa-platform: fix license package generation
For some reason bitbake doesn't like references from outside the ${S}?
directory for license files, and breaks during generation of -lic
packages with:

ERROR: Task (/.../poky/meta-ofdpa/recipes-ofdpa/ofdpa/ofdpa-platform_1.0.bb:do_package) failed with exit code '134'
Pseudo log:
path mismatch [6 links]: ino 1318598 db '/tmp/yocto/kirkstone/work/all-poky-linux/ofdpa-platform/1.0-r0/image/usr/share/licenses/ofdpa-platform/generic_Broadcom-OpenBCM' req '/tmp/yocto/kirkstone/work/all-poky-linux/ofdpa-platform/1.0-r0/LICENSE.Broadcom-OpenBCM'.
Setup complete, sending SIGUSR1 to pid 3145507.

Fix/work around this by putting the license file into the git/
directory.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>