ofdpa: do not disable platforms manually
When enabling BCM_PTL_SPT ("ParTiaL SuPporT"), the SDK will
automatically disable all platforms by default by generating -DNO_BCM_*
symbols [1] for every platform that is not explicitly enabled through a

BCM_FOO = 1

line in the make/Make.local.

Since every platform's Make.local sets its required platforms, we can
just leave the disabling of platforms to the SDK.

This also drops the need for adding the -DBCM_FOO lines to CFLAGS in the
platform Make.local, which then also silences GCC complaints about the
redefinition of these macros, like:

in file included from ../../../sdk/include/soc/mcm/allenum.h:105,
                 from ../../../sdk/include/soc/defs.h:21,
                 from ../../../sdk/include/soc/cm.h:16,
                 from ../../../sdk/include/soc/drv.h:34,
                 from ../../../mapping/driver/driver_counter.c:33:
../../../sdk/include/soc/mcm/enum_max.h:489: warning: "BCM_56965_A0" redefined
  489 | #  define BCM_56965_A0
      |

Additionally, this then removes the need to add extra CFLAGS for implied
platform support, like Helix 4 (BCM56340) needing BCM56640 support
enabled as well to build.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>